export interface MasteryRule {
  name: string;
  category: string;
  requirementsCount: number;
  specialties: string[]; // Nomes oficiais das especialidades
  isGlobalArea?: boolean; // Se true, qualquer uma da área/sigla serve
  siglas?: string[]; // Siglas correspondentes no banco de dados (ex: 'HM', 'EN', 'AP', etc.)
}

export const MASTERY_RULES: MasteryRule[] = [
  // 001 - Mestrado em ADRA (Global: 7 especialidades de ADRA)
  {
    name: "Mestrado em ADRA",
    category: "ADRA",
    requirementsCount: 7,
    specialties: [],
    isGlobalArea: true,
    siglas: ['AD']
  },

  // 002 - Mestrado em Artes e Habilidades Manuais (Global: 7 especialidades de Artes e Habilidades Manuais)
  {
    name: "Mestrado em Artes e Habilidades Manuais",
    category: "Artes e Habilidades Manuais",
    requirementsCount: 7,
    specialties: [],
    isGlobalArea: true,
    siglas: ['HM']
  },

  // 003 - Mestrado em Atividades Agrícolas (Global: 7 especialidades de Atividades Agrícolas)
  {
    name: "Mestrado em Atividades Agrícolas",
    category: "Atividades Agrícolas",
    requirementsCount: 7,
    specialties: [],
    isGlobalArea: true,
    siglas: ['AG']
  },

  // 004 - Mestrado em Testificação (Lista Fechada oficial de 50 especialidades)
  {
    name: "Mestrado em Testificação",
    category: "Atividades Missionárias",
    requirementsCount: 7,
    specialties: [
      "Adoração cristã",
      "Apocalipse",
      "Arqueologia bíblica",
      "Arte da pregação cristã",
      "Arte da pregação cristã - avançado",
      "Arte de contar histórias cristãs",
      "Arte em fantoches",
      "Arte em fantoches - avançado",
      "Asseio e cortesia cristã",
      "Aventuras com Cristo",
      "Aventuras com Cristo - avançado",
      "Braille",
      "Cidadania cristã",
      "Colportagem",
      "Criacionismo",
      "Criacionismo - avançado",
      "Crítico de mídia",
      "Dramatização cristã",
      "Escatologia",
      "Espírito de Profecia",
      "Etnologia missionária",
      "Evangelismo pessoal",
      "Evangelismo web",
      "Evangelismo web - avançado",
      "Historiador eclesiástico",
      "Intercessor",
      "Interpretação bíblica",
      "Investigador bíblico",
      "Liderança juvenil",
      "Língua de sinais",
      "Língua de sinais - avançado",
      "Lives - transmissão de cultos online",
      "Livro de Daniel",
      "Marcação bíblica",
      "Marcação bíblica - avançado",
      "Mensageira de Deus",
      "Mordomia",
      "Pacificador",
      "Pacificador - avançado",
      "Parábolas de Jesus",
      "Pioneiros adventistas",
      "Pregador evangelista",
      "Pregador evangelista - avançado",
      "Relacionamentos saudáveis",
      "Santuário",
      "Sonoplastia",
      "Sonoplastia - avançado",
      "Temperança",
      "Testemunho juvenil",
      "Vida familiar"
    ],
    isGlobalArea: false,
    siglas: ['AM', 'MA']
  },

  // 005 - Mestrado em Atividades Profissionais (Lista Fechada oficial de 50 especialidades)
  {
    name: "Mestrado em Atividades Profissionais",
    category: "Atividades Profissionais",
    requirementsCount: 7,
    specialties: [
      "Administração",
      "Alvenaria",
      "Barbearia",
      "Biblioteconomia",
      "Cães - cuidado e treinamento",
      "Carpintaria",
      "Colocação de papel de parede",
      "Conserto de sapatos",
      "Contabilidade",
      "Corte e costura",
      "Corte e costura - avançado",
      "Cuidado e manutenção de violões",
      "Cuidados e manutenção de violões",
      "Desenvolvimento de software",
      "Eletricidade",
      "Eletrônica",
      "Encadernação",
      "Evangelismo",
      "Fotografia",
      "Hidráulica",
      "Informática programável",
      "Intérprete de língua de sinais",
      "Jornalismo",
      "Logística",
      "Magistério",
      "Manutenção de bicicletas",
      "Marcenaria",
      "Marketing",
      "Marketing - avançado",
      "Marketing avançado",
      "Mecânica automotiva",
      "Mecânica de pequenos motores",
      "Modelagem têxtil",
      "Montagem e manutenção de computadores",
      "Noções de direito",
      "Noções de economia",
      "Ofício de alfaiate",
      "Operação e manutenção de impressoras",
      "Pintura de paredes exteriores",
      "Pintura de paredes interiores",
      "Produção de vídeo",
      "Radioamadorismo",
      "Restauro e conservação documental",
      "Secretariado",
      "Segurança contra incêndios",
      "Silvicultura",
      "Soldagem",
      "Taquigrafia",
      "Tipografia",
      "Vendas",
      "Web designer",
      "Web designer - avançado",
      "Web designer avançado"
    ],
    isGlobalArea: false,
    siglas: ['AP']
  },

  // 006 - Mestrado em Ciência e Tecnologia
  {
    name: "Mestrado em Ciência e Tecnologia",
    category: "Ciência e Tecnologia",
    requirementsCount: 7,
    specialties: [
      "Computação I",
      "Computação II",
      "Computação III",
      "Computação IV",
      "Computação V",
      "Desenvolvimento de software",
      "Eletrônica",
      "Experimentos científicos",
      "Física",
      "Habilidades em matemática I",
      "Habilidades em matemática II",
      "Informática programável",
      "Internet",
      "Internet - avançado",
      "Metodologia de estudo",
      "Óptica",
      "Química",
      "Segurança nas redes sociais",
      "Web designer",
      "Web designer - avançado",
      "Web designer avançado"
    ],
    isGlobalArea: false,
    siglas: ['AP', 'CT']
  },

  // 007 - Mestrado em Aquática
  {
    name: "Mestrado em Aquática",
    category: "Atividades Aquáticas",
    requirementsCount: 7,
    specialties: [
      "Caiaque",
      "Calaque",
      "Canoagem",
      "Esqui aquático",
      "Mergulho autônomo",
      "Mergulho livre",
      "Natação principiante I",
      "Natação principiante II",
      "Natação intermediário I",
      "Natação intermediário II",
      "Natação avançado",
      "Navegação",
      "Rafting",
      "Remo",
      "Saltos ornamentais",
      "Salvamento de afogados",
      "Salvamento de afogados - avançado",
      "Salvamento de afogados avançado",
      "Segurança básica na água",
      "Vela"
    ],
    isGlobalArea: false,
    siglas: ['AA', 'AR']
  },

  // 008 - Mestrado em Esportes
  {
    name: "Mestrado em Esportes",
    category: "Atividades Recreativas",
    requirementsCount: 7,
    specialties: [
      "Arco e flecha",
      "Atletismo",
      "Basquete",
      "Ciclismo",
      "Ciclismo avançado",
      "Ciclismo - avançado",
      "Cultura física",
      "Equitação",
      "Escalada",
      "Escalada - avançado",
      "Esportes adaptados",
      "Esqui aquático",
      "Exploração de cavernas",
      "Exploração de cavernas - avançado",
      "Futebol",
      "Futsal",
      "Ginástica acrobática",
      "Handebol",
      "Mountain biking",
      "Rapel",
      "Rapel - avançado",
      "Rapel - instrutor",
      "Softbol",
      "Tênis de mesa",
      "Triathlon",
      "Vôlei"
    ],
    isGlobalArea: false,
    siglas: ['AR', 'ES']
  },

  // 009 - Mestrado em Vida Campestre
  {
    name: "Mestrado em Vida Campestre",
    category: "Vida Campestre",
    requirementsCount: 7,
    specialties: [
      "Acampamento consciente",
      "Acampamento em baixas temperaturas",
      "Acampamento I",
      "Acampamento II",
      "Acampamento III",
      "Acampamento IV",
      "Acampamento seguro",
      "Acampamento seguro - avançado",
      "Acampamento seguro avançado",
      "Arte de acampar",
      "Artes mateiras",
      "Comida mateira",
      "Construções rústicas de grande porte",
      "Cozinha com forno holandês",
      "Escalada em árvores",
      "Excursionismo pedestre",
      "Excursionismo pedestre - avançado",
      "Excursionismo pedestre avançado",
      "Excursionismo pedestre com mochila",
      "Excursionismo pedestre com mochila - avançado",
      "Excursionismo pedestre com mochila avançado",
      "Excursionismo pedestre na neve",
      "Fogueiras e cozinha ao ar livre",
      "Liderança campestre",
      "Liderança campestre - avançado",
      "Liderança campestre avançado",
      "Liderança na selva",
      "Liderança na selva - avançado",
      "Liderança na selva avançado",
      "Mapa e bússola",
      "Nós e amarras",
      "Nós e amarras - avançado",
      "Nós e amarras avançado",
      "Orientação com GPS",
      "Pioneirias",
      "Pioneirias - avançado",
      "Pioneirias avançado",
      "Pioneiras",
      "Pioneiras - avançado",
      "Pioneirismo",
      "Plantas silvestres comestíveis",
      "Trilha de sinais",
      "Vida silvestre"
    ],
    isGlobalArea: false,
    siglas: ['VC', 'AR']
  },

  // 010 - Mestrado em Atividades Recreativas
  {
    name: "Mestrado em Atividades Recreativas",
    category: "Atividades Recreativas",
    requirementsCount: 7,
    specialties: [
      "Aquarismo",
      "Boliche",
      "Bolinha de gude",
      "Carrinho de rolimã",
      "Carrinho de rolima",
      "Colecionador",
      "Cubo mágico",
      "Evolução em ordem unida",
      "Fanfarra",
      "Filatelia",
      "Futebol de botão",
      "Geocaching",
      "Geocaching - avançado",
      "Geocaching avançado",
      "Nós e amarras",
      "Nós e amarras - avançado",
      "Numismática",
      "Numismática - avançado",
      "Numismática avançado",
      "Ordem unida",
      "Ordem unida - avançado",
      "Ordem unida - instrutor",
      "Patins",
      "Pião",
      "Pipas",
      "Segurança básica na água",
      "Skate",
      "Slackline",
      "Troca de pins",
      "Viagem e turismo",
      "Viagem e turismo - avançado",
      "Viagem e turismo avançado"
    ],
    isGlobalArea: false,
    siglas: ['AR']
  },

  // 011 - Mestrado em Saúde
  {
    name: "Mestrado em Saúde",
    category: "Saúde",
    requirementsCount: 7,
    specialties: [
      "Alerta vermelho",
      "Anatomia humana básica",
      "Bactérias",
      "Bacteria",
      "Bioquímica",
      "Biossegurança",
      "Citologia",
      "Coração e circulação",
      "Digestão",
      "Enfermagem básica",
      "Hereditariedade",
      "Higiene oral",
      "Higiene oral - avançado",
      "Higiene oral avançado",
      "Inteligência emocional",
      "Microscopia",
      "Nutrição",
      "Nutrição - avançado",
      "Nutrição avançado",
      "Ossos, músculos e articulações",
      "Plantas medicinais",
      "Prevenção de doenças tropicais",
      "Prevenção de doenças tropicals",
      "Primeiros socorros - básico",
      "Primeiros socorros - intermediário",
      "Primeiros socorros - avançado",
      "Protozoários",
      "Reanimação cardiopulmonar",
      "Remédios da natureza",
      "Resgate básico",
      "Sangue e defesas do corpo",
      "Saúde e cura",
      "Saúde mental",
      "Sexualidade humana",
      "Sistema nervoso",
      "Sistema respiratório",
      "Vacinas",
      "Vírus",
      "Zoonoses"
    ],
    isGlobalArea: false,
    siglas: ['CS', 'SC', 'SA']
  },

  // 012 - Mestrado em Zoologia
  {
    name: "Mestrado em Zoologia",
    category: "Estudo da Natureza",
    requirementsCount: 7,
    specialties: [
      "Abelhas e vespas",
      "Anfíbios",
      "Anfibios",
      "Anfíbios - avançado",
      "Anfibios avançado",
      "Animais migratórios",
      "Animais nocivos",
      "Animais noturnos",
      "Animais peçonhentos",
      "Aranhas",
      "Araras, papagaios e periquitos",
      "Aves",
      "Aves - avançado",
      "Aves avançado",
      "Aves de estimação",
      "Aves de rapina",
      "Aves domésticas",
      "Cães",
      "Camelos",
      "Cetáceos",
      "Cigarras",
      "Crustáceos",
      "Equinodermos",
      "Fauna marinha",
      "Felinos",
      "Felinos - avançado",
      "Felinos avançado",
      "Formigas",
      "Insetos",
      "Insetos - avançado",
      "Insetos avançado",
      "Mamíferos",
      "Mamiferos",
      "Mamíferos - avançado",
      "Mamíferos avançado",
      "Mamíferos marinhos",
      "Mariposas e borboletas",
      "Marsupiais",
      "Marsupials",
      "Mimetismo e camuflagem",
      "Moluscos",
      "Moluscos - avançado",
      "Moluscos avançado",
      "Morcegos",
      "Morcegos - avançado",
      "Morcegos avançado",
      "Odonata",
      "Peixes",
      "Peixes ornamentais",
      "Pequenos mamíferos de estimação",
      "Poríferos e cnidários",
      "Primatas",
      "Quelônios",
      "Rastreio de animais",
      "Rastreio de animais - avançado",
      "Rastreio de animais avançado",
      "Rebanhos domésticos",
      "Répteis",
      "Répteis - avançado",
      "Répteis avançado",
      "Tubarões",
      "Vermes",
      "Vermes - avançado",
      "Vermes avançado",
      "Zoonoses"
    ],
    isGlobalArea: false,
    siglas: ['EN']
  },

  // 013 - Mestrado em Ecologia
  {
    name: "Mestrado em Ecologia",
    category: "Estudo da Natureza",
    requirementsCount: 7,
    specialties: [
      "Animais ameaçados de extinção",
      "Araras, papagaios e periquitos",
      "Compostagem doméstica",
      "Conservação ambiental",
      "Ecologia",
      "Ecologia - avançado",
      "Ecologia avançado",
      "Energias renováveis",
      "Estuário",
      "Preservação de recursos hídricos",
      "Quedas d'água",
      "Quelônios",
      "Reciclagem e sustentabilidade",
      "Reciclagem e sustentabilidade - avançado",
      "Reciclagem e sustentabilidade avançado"
    ],
    isGlobalArea: false,
    siglas: ['EN']
  },

  // 014 - Mestrado em Botânica
  {
    name: "Mestrado em Botânica",
    category: "Estudo da Natureza",
    requirementsCount: 7,
    specialties: [
      "Algas",
      "Arbustos",
      "Arbustos - avançado",
      "Arbustos avançado",
      "Árvores",
      "Arvores",
      "Árvores - avançado",
      "Arvores- avançado",
      "Arvores avançado",
      "Briófitas",
      "Bromélias",
      "Cactos",
      "Cactos - avançado",
      "Cactos avançado",
      "Ervas",
      "Eucaliptos",
      "Fisiologia vegetal",
      "Flores",
      "Flores - avançado",
      "Flores avançado",
      "Gramíneas",
      "Gramineas",
      "Liquens",
      "Orquídeas",
      "Orquideas",
      "Orquídeas - avançado",
      "Orquídeas-avançado",
      "Orquídeas avançado",
      "Palmeiras",
      "Plantas carnívoras",
      "Plantas caseiras",
      "Samambaias",
      "Sementes",
      "Sementes - avançado",
      "Sementes avançado"
    ],
    isGlobalArea: false,
    siglas: ['EN']
  },

  // 015 - Mestrado em Habilidades Domésticas (Global: 7 especialidades de Habilidades Domésticas)
  {
    name: "Mestrado em Habilidades Domésticas",
    category: "Habilidades Domésticas",
    requirementsCount: 7,
    specialties: [],
    isGlobalArea: true,
    siglas: ['HD']
  },

  // 016 - Mestrado em Ensinos Bíblicos (Global: 14 especialidades em Ensinos Bíblicos)
  {
    name: "Mestrado em Ensinos Bíblicos",
    category: "Ensinos Bíblicos",
    requirementsCount: 14,
    specialties: [],
    isGlobalArea: true,
    siglas: ['EB', 'AM-EB', 'AM']
  }
];
