import { BibleBook } from '../types';

export const CANONICAL_BIBLE_BOOKS: BibleBook[] = [
  // Antigo Testamento (39 Livros)
  { id: 1, book_name: 'Gênesis', book_abbrev: 'Gn', total_chapters: 50, testament: 'Antigo' },
  { id: 2, book_name: 'Êxodo', book_abbrev: 'Ex', total_chapters: 40, testament: 'Antigo' },
  { id: 3, book_name: 'Levítico', book_abbrev: 'Lv', total_chapters: 27, testament: 'Antigo' },
  { id: 4, book_name: 'Números', book_abbrev: 'Nm', total_chapters: 36, testament: 'Antigo' },
  { id: 5, book_name: 'Deuteronômio', book_abbrev: 'Dt', total_chapters: 34, testament: 'Antigo' },
  { id: 6, book_name: 'Josué', book_abbrev: 'Js', total_chapters: 24, testament: 'Antigo' },
  { id: 7, book_name: 'Juízes', book_abbrev: 'Jz', total_chapters: 21, testament: 'Antigo' },
  { id: 8, book_name: 'Rute', book_abbrev: 'Rt', total_chapters: 4, testament: 'Antigo' },
  { id: 9, book_name: '1 Samuel', book_abbrev: '1Sm', total_chapters: 31, testament: 'Antigo' },
  { id: 10, book_name: '2 Samuel', book_abbrev: '2Sm', total_chapters: 24, testament: 'Antigo' },
  { id: 11, book_name: '1 Reis', book_abbrev: '1Rs', total_chapters: 22, testament: 'Antigo' },
  { id: 12, book_name: '2 Reis', book_abbrev: '2Rs', total_chapters: 25, testament: 'Antigo' },
  { id: 13, book_name: '1 Crônicas', book_abbrev: '1Cr', total_chapters: 29, testament: 'Antigo' },
  { id: 14, book_name: '2 Crônicas', book_abbrev: '2Cr', total_chapters: 36, testament: 'Antigo' },
  { id: 15, book_name: 'Esdras', book_abbrev: 'Ed', total_chapters: 10, testament: 'Antigo' },
  { id: 16, book_name: 'Neemias', book_abbrev: 'Ne', total_chapters: 13, testament: 'Antigo' },
  { id: 17, book_name: 'Ester', book_abbrev: 'Et', total_chapters: 10, testament: 'Antigo' },
  { id: 18, book_name: 'Jó', book_abbrev: 'Jó', total_chapters: 42, testament: 'Antigo' },
  { id: 19, book_name: 'Salmos', book_abbrev: 'Sl', total_chapters: 150, testament: 'Antigo' },
  { id: 20, book_name: 'Provérbios', book_abbrev: 'Pv', total_chapters: 31, testament: 'Antigo' },
  { id: 21, book_name: 'Eclesiastes', book_abbrev: 'Ec', total_chapters: 12, testament: 'Antigo' },
  { id: 22, book_name: 'Cantares', book_abbrev: 'Ct', total_chapters: 8, testament: 'Antigo' },
  { id: 23, book_name: 'Isaías', book_abbrev: 'Is', total_chapters: 66, testament: 'Antigo' },
  { id: 24, book_name: 'Jeremias', book_abbrev: 'Jr', total_chapters: 52, testament: 'Antigo' },
  { id: 25, book_name: 'Lamentações', book_abbrev: 'Lm', total_chapters: 5, testament: 'Antigo' },
  { id: 26, book_name: 'Ezequiel', book_abbrev: 'Ez', total_chapters: 48, testament: 'Antigo' },
  { id: 27, book_name: 'Daniel', book_abbrev: 'Dn', total_chapters: 12, testament: 'Antigo' },
  { id: 28, book_name: 'Oseias', book_abbrev: 'Os', total_chapters: 14, testament: 'Antigo' },
  { id: 29, book_name: 'Joel', book_abbrev: 'Jl', total_chapters: 3, testament: 'Antigo' },
  { id: 30, book_name: 'Amós', book_abbrev: 'Am', total_chapters: 9, testament: 'Antigo' },
  { id: 31, book_name: 'Obadias', book_abbrev: 'Ob', total_chapters: 1, testament: 'Antigo' },
  { id: 32, book_name: 'Jonas', book_abbrev: 'Jn', total_chapters: 4, testament: 'Antigo' },
  { id: 33, book_name: 'Miqueias', book_abbrev: 'Mq', total_chapters: 7, testament: 'Antigo' },
  { id: 34, book_name: 'Naum', book_abbrev: 'Na', total_chapters: 3, testament: 'Antigo' },
  { id: 35, book_name: 'Habacuque', book_abbrev: 'Hb', total_chapters: 3, testament: 'Antigo' },
  { id: 36, book_name: 'Sofonias', book_abbrev: 'Sf', total_chapters: 3, testament: 'Antigo' },
  { id: 37, book_name: 'Ageu', book_abbrev: 'Ag', total_chapters: 2, testament: 'Antigo' },
  { id: 38, book_name: 'Zacarias', book_abbrev: 'Zc', total_chapters: 14, testament: 'Antigo' },
  { id: 39, book_name: 'Malaquias', book_abbrev: 'Ml', total_chapters: 4, testament: 'Antigo' },

  // Novo Testamento (27 Livros)
  { id: 40, book_name: 'Mateus', book_abbrev: 'Mt', total_chapters: 28, testament: 'Novo' },
  { id: 41, book_name: 'Marcos', book_abbrev: 'Mc', total_chapters: 16, testament: 'Novo' },
  { id: 42, book_name: 'Lucas', book_abbrev: 'Lc', total_chapters: 24, testament: 'Novo' },
  { id: 43, book_name: 'João', book_abbrev: 'Jo', total_chapters: 21, testament: 'Novo' },
  { id: 44, book_name: 'Atos', book_abbrev: 'At', total_chapters: 28, testament: 'Novo' },
  { id: 45, book_name: 'Romanos', book_abbrev: 'Rm', total_chapters: 16, testament: 'Novo' },
  { id: 46, book_name: '1 Coríntios', book_abbrev: '1Co', total_chapters: 16, testament: 'Novo' },
  { id: 47, book_name: '2 Coríntios', book_abbrev: '2Co', total_chapters: 13, testament: 'Novo' },
  { id: 48, book_name: 'Gálatas', book_abbrev: 'Gl', total_chapters: 6, testament: 'Novo' },
  { id: 49, book_name: 'Efésios', book_abbrev: 'Ef', total_chapters: 6, testament: 'Novo' },
  { id: 50, book_name: 'Filipenses', book_abbrev: 'Fp', total_chapters: 4, testament: 'Novo' },
  { id: 51, book_name: 'Colossenses', book_abbrev: 'Cl', total_chapters: 4, testament: 'Novo' },
  { id: 52, book_name: '1 Tessalonicenses', book_abbrev: '1Ts', total_chapters: 5, testament: 'Novo' },
  { id: 53, book_name: '2 Tessalonicenses', book_abbrev: '2Ts', total_chapters: 3, testament: 'Novo' },
  { id: 54, book_name: '1 Timóteo', book_abbrev: '1Tm', total_chapters: 6, testament: 'Novo' },
  { id: 55, book_name: '2 Timóteo', book_abbrev: '2Tm', total_chapters: 4, testament: 'Novo' },
  { id: 56, book_name: 'Tito', book_abbrev: 'Tt', total_chapters: 3, testament: 'Novo' },
  { id: 57, book_name: 'Filemom', book_abbrev: 'Fm', total_chapters: 1, testament: 'Novo' },
  { id: 58, book_name: 'Hebreus', book_abbrev: 'Hb', total_chapters: 13, testament: 'Novo' },
  { id: 59, book_name: 'Tiago', book_abbrev: 'Tg', total_chapters: 5, testament: 'Novo' },
  { id: 60, book_name: '1 Pedro', book_abbrev: '1Pe', total_chapters: 5, testament: 'Novo' },
  { id: 61, book_name: '2 Pedro', book_abbrev: '2Pe', total_chapters: 3, testament: 'Novo' },
  { id: 62, book_name: '1 João', book_abbrev: '1Jo', total_chapters: 5, testament: 'Novo' },
  { id: 63, book_name: '2 João', book_abbrev: '2Jo', total_chapters: 1, testament: 'Novo' },
  { id: 64, book_name: '3 João', book_abbrev: '3Jo', total_chapters: 1, testament: 'Novo' },
  { id: 65, book_name: 'Judas', book_abbrev: 'Jd', total_chapters: 1, testament: 'Novo' },
  { id: 66, book_name: 'Apocalipse', book_abbrev: 'Ap', total_chapters: 22, testament: 'Novo' }
];
