<?php
require_once '../includes/config.php';
require_once '../includes/conexao.php';

$current_page = 'quiz';
$action = isset($_GET['action']) ? $_GET['action'] : 'upload';
$msg = '';
$err = '';

$driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);

function ensureQuizTables(PDO $pdo, $driver) {
    try {
        if ($driver === 'pgsql') {
            $pdo->exec('CREATE TABLE IF NOT EXISTS public."quiz_categorias" (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome TEXT)');
            $pdo->exec('CREATE TABLE IF NOT EXISTS public."quiz_questoes" (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                categoria_id BIGINT NULL,
                questao TEXT NULL,
                opicao_1 TEXT NULL,
                opicao_2 TEXT NULL,
                opicao_3 TEXT NULL,
                opicao_4 TEXT NULL,
                opicao_correta BIGINT NULL,
                nivel_dificuldade TEXT NULL,
                codigo TEXT NULL,
                CONSTRAINT quiz_questoes_duplicate_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES public."quiz_categorias"(id)
            )');
        } else {
            $pdo->exec('CREATE TABLE IF NOT EXISTS quiz_categorias (id BIGINT AUTO_INCREMENT PRIMARY KEY, nome TEXT)');
            $pdo->exec('CREATE TABLE IF NOT EXISTS quiz_questoes (
                id BIGINT AUTO_INCREMENT PRIMARY KEY,
                categoria_id BIGINT NULL,
                questao TEXT NULL,
                opicao_1 TEXT NULL,
                opicao_2 TEXT NULL,
                opicao_3 TEXT NULL,
                opicao_4 TEXT NULL,
                opicao_correta BIGINT NULL,
                nivel_dificuldade TEXT NULL,
                codigo TEXT NULL,
                INDEX idx_cat (categoria_id)
            )');
        }
    } catch (Exception $e) {}
}

ensureQuizTables($pdo, $driver);

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (isset($_POST['add_categoria'])) {
        $nome = trim($_POST['nome']);
        if ($nome !== '') {
            $table = $driver === 'pgsql' ? 'public."quiz_categorias"' : 'quiz_categorias';
            $stmt = $pdo->prepare("INSERT INTO {$table} (nome) VALUES (?)");
            $stmt->execute([$nome]);
            $msg = 'Categoria adicionada';
        }
    } elseif (isset($_POST['add_question'])) {
        $table = $driver === 'pgsql' ? 'public."quiz_questoes"' : 'quiz_questoes';
        $cat = isset($_POST['categoria_id']) && $_POST['categoria_id'] !== '' ? (int)$_POST['categoria_id'] : null;
        $questao = trim($_POST['questao']);
        $o1 = trim($_POST['opicao_1']);
        $o2 = trim($_POST['opicao_2']);
        $o3 = trim($_POST['opicao_3']);
        $o4 = trim($_POST['opicao_4']);
        $cor = (int)$_POST['opicao_correta'];
        $niv = trim($_POST['nivel_dificuldade']);
        $cod = trim($_POST['codigo']);
        if ($questao !== '' && $o1 !== '' && $o2 !== '' && $o3 !== '' && $o4 !== '' && $cor >= 1 && $cor <= 4) {
            $sql = "INSERT INTO {$table} (categoria_id, questao, opicao_1, opicao_2, opicao_3, opicao_4, opicao_correta, nivel_dificuldade, codigo) VALUES (?,?,?,?,?,?,?,?,?)";
            $stmtI = $pdo->prepare($sql);
            $stmtI->execute([$cat, $questao, $o1, $o2, $o3, $o4, $cor, $niv, $cod]);
            $msg = 'Questão adicionada';
        } else {
            $err = 'Preencha todos os campos e selecione a resposta correta (1-4).';
        }
    } elseif (isset($_POST['import_csv'])) {
        if (isset($_FILES['csv_file']) && $_FILES['csv_file']['error'] === UPLOAD_ERR_OK) {
            $fh = fopen($_FILES['csv_file']['tmp_name'], 'r');
            if ($fh) {
                $header = fgetcsv($fh, 0, ',');
                $map = [];
                foreach ($header as $i => $col) {
                    $key = strtolower(trim($col));
                    $map[$key] = $i;
                }
                $required = ['questao','opicao_1','opicao_2','opicao_3','opicao_4','opicao_correta'];
                foreach ($required as $req) {
                    if (!isset($map[$req])) { $err = 'CSV inválido: colunas obrigatórias ausentes'; break; }
                }
                $inserted = 0;
                if (!$err) {
                    $table = $driver === 'pgsql' ? 'public."quiz_questoes"' : 'quiz_questoes';
                    $sql = "INSERT INTO {$table} (categoria_id, questao, opicao_1, opicao_2, opicao_3, opicao_4, opicao_correta, nivel_dificuldade, codigo) VALUES (?,?,?,?,?,?,?,?,?)";
                    $stmtI = $pdo->prepare($sql);
                    while (($row = fgetcsv($fh, 0, ',')) !== false) {
                        $cat = isset($map['categoria_id']) ? (trim($row[$map['categoria_id']]) !== '' ? (int)$row[$map['categoria_id']] : null) : null;
                        $questao = $row[$map['questao']] ?? null;
                        $o1 = $row[$map['opicao_1']] ?? null;
                        $o2 = $row[$map['opicao_2']] ?? null;
                        $o3 = $row[$map['opicao_3']] ?? null;
                        $o4 = $row[$map['opicao_4']] ?? null;
                        $cor = isset($map['opicao_correta']) ? (trim($row[$map['opicao_correta']]) !== '' ? (int)$row[$map['opicao_correta']] : null) : null;
                        $niv = isset($map['nivel_dificuldade']) ? ($row[$map['nivel_dificuldade']] ?? null) : null;
                        $cod = isset($map['codigo']) ? ($row[$map['codigo']] ?? null) : null;
                        if ($questao && $o1 && $o2 && $o3 && $o4) {
                            $stmtI->execute([$cat, $questao, $o1, $o2, $o3, $o4, $cor, $niv, $cod]);
                            $inserted++;
                        }
                    }
                    fclose($fh);
                    $msg = "Importadas {$inserted} questões";
                }
            } else {
                $err = 'Não foi possível ler o arquivo';
            }
        } else {
            $err = 'Arquivo CSV não enviado';
        }
    }
    elseif (isset($_POST['reset_quiz'])) {
        try {
            if ($driver === 'pgsql') {
                $pdo->exec('TRUNCATE TABLE public."quiz_questoes" RESTART IDENTITY');
            } else {
                $pdo->exec('TRUNCATE TABLE quiz_questoes');
            }
            $msg = 'Quiz resetado: todas as perguntas foram removidas.';
        } catch (Exception $e) {
            $err = 'Falha ao resetar o quiz: ' . $e->getMessage();
        }
    }
}

require_once '../includes/admin_header.php';
?>

<h2>Quiz Bíblico</h2>
<?php if ($msg): ?><div style="background:#d4edda;color:#155724;padding:10px;margin-bottom:20px;border-radius:4px;"><?php echo $msg; ?></div><?php endif; ?>
<?php if ($err): ?><div style="background:#fff3cd;color:#856404;padding:10px;margin-bottom:20px;border-radius:4px;"><?php echo $err; ?></div><?php endif; ?>

<div class="form-container" style="margin-bottom:16px;">
    <h3>Manutenção</h3>
    <form method="POST" onsubmit="return confirm('Tem certeza que deseja resetar o quiz (apenas perguntas)?');">
        <button type="submit" name="reset_quiz" class="btn-delete">Resetar Quiz (remover perguntas)</button>
    </form>
</div>

<div class="form-container" style="margin-bottom:16px;">
    <h3>Adicionar Categoria</h3>
    <form method="POST">
        <div class="form-group">
            <label>Nome</label>
            <input type="text" name="nome" class="form-control" required>
        </div>
        <button type="submit" name="add_categoria" class="btn-new">Salvar</button>
    </form>
</div>

<div class="form-container" style="margin-bottom:16px;">
    <h3>Adicionar Questão</h3>
    <form method="POST">
        <div class="form-group">
            <label>Categoria</label>
            <select name="categoria_id" class="form-control">
                <option value="">Nulo</option>
                <?php
                $tableC = $driver === 'pgsql' ? 'public."quiz_categorias"' : 'quiz_categorias';
                $stC = $pdo->query("SELECT id, nome FROM {$tableC} ORDER BY nome ASC");
                while ($c = $stC->fetch(PDO::FETCH_ASSOC)) {
                    echo "<option value=\"{$c['id']}\">".htmlspecialchars($c['nome'])."</option>";
                }
                ?>
            </select>
        </div>
        <div class="form-group">
            <label>Questão</label>
            <textarea name="questao" class="form-control" rows="3" required></textarea>
        </div>
        <div class="form-group"><label>Opção A</label><input type="text" name="opicao_1" class="form-control" required></div>
        <div class="form-group"><label>Opção B</label><input type="text" name="opicao_2" class="form-control" required></div>
        <div class="form-group"><label>Opção C</label><input type="text" name="opicao_3" class="form-control" required></div>
        <div class="form-group"><label>Opção D</label><input type="text" name="opicao_4" class="form-control" required></div>
        <div class="form-group">
            <label>Resposta Correta</label>
            <select name="opicao_correta" class="form-control" required>
                <option value="1">A</option>
                <option value="2">B</option>
                <option value="3">C</option>
                <option value="4">D</option>
            </select>
        </div>
        <div class="form-group"><label>Nível de Dificuldade</label><input type="text" name="nivel_dificuldade" class="form-control"></div>
        <div class="form-group"><label>Código</label><input type="text" name="codigo" class="form-control"></div>
        <button type="submit" name="add_question" class="btn-new">Salvar Questão</button>
    </form>
</div>

<div class="form-container">
    <h3>Importar CSV de Questões</h3>
    <form method="POST" enctype="multipart/form-data">
        <div class="form-group">
            <label>Arquivo CSV (modelo Supabase quiz_questoes)</label>
            <input type="file" name="csv_file" class="form-control" accept=".csv" required>
        </div>
        <button type="submit" name="import_csv" class="btn-new">Importar</button>
    </form>
</div>

<?php
$tableQ = $driver === 'pgsql' ? 'public."quiz_questoes"' : 'quiz_questoes';
$tableC = $driver === 'pgsql' ? 'public."quiz_categorias"' : 'quiz_categorias';
$stmt = $pdo->query("SELECT q.id, q.questao, q.opicao_correta, q.categoria_id, q.nivel_dificuldade, q.codigo, c.nome AS categoria FROM {$tableQ} q LEFT JOIN {$tableC} c ON c.id = q.categoria_id ORDER BY q.id DESC LIMIT 20");
$rows = $stmt->fetchAll(PDO::FETCH_ASSOC);
?>
<h3 style="margin-top:20px;">Últimas Questões</h3>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Categoria</th>
            <th>Questão</th>
            <th>Correta</th>
            <th>Nível</th>
            <th>Código</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($rows as $r): ?>
        <tr>
            <td><?php echo (int)$r['id']; ?></td>
            <td><?php echo htmlspecialchars($r['categoria'] ?? ''); ?></td>
            <td><?php echo htmlspecialchars(substr($r['questao'],0,100)); ?></td>
            <td><?php echo htmlspecialchars($r['opicao_correta'] ?? ''); ?></td>
            <td><?php echo htmlspecialchars($r['nivel_dificuldade'] ?? ''); ?></td>
            <td><?php echo htmlspecialchars($r['codigo'] ?? ''); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php require_once '../includes/admin_footer.php'; ?>
